import Foundation

/// UI text in 43 languages, one row per language in the order of the properties below.
/// Where macOS has its own wording, the row carries it, taken from the system's localization
/// tables: Open Recent and Clear Menu from AppKit's MenuCommands, Cancel from its Common table.
/// A row that doesn't have every entry falls back to English as a whole.
struct Strings {
    private let v: [String]

    var open: String { v[0] }
    var paste: String { v[1] }
    var dropHint: String { v[2] }
    var formatHint: String { v[3] }
    var decks: String { v[4] }
    var clipboard: String { v[5] }
    var remove: String { v[6] }
    var showInFinder: String { v[7] }
    var noCards: String { v[8] }
    var cantRead: String { v[9] }
    var question: String { v[10] }
    var answer: String { v[11] }
    var clickFront: String { v[12] }
    var clickBack: String { v[13] }
    var dontKnow: String { v[14] }
    var know: String { v[15] }
    var shuffle: String { v[16] }
    var reset: String { v[17] }
    var resetTitle: String { v[18] }
    var resetBody: String { v[19] }
    var resetButton: String { v[20] }
    var cancel: String { v[21] }
    var done: String { v[22] }
    var total: String { v[23] }
    var retryMissed: String { v[24] }
    var retryAll: String { v[25] }
    var perfect: String { v[26] }
    var bad: String { v[27] }
    var normal: String { v[28] }
    func unrated(_ n: Int) -> String { String(format: v[29], n) }
    var listen: String { v[30] }
    var flip: String { v[31] }
    var previous: String { v[32] }
    var next: String { v[33] }
    var deck: String { v[34] }
    var openRecent: String { v[35] }
    var clearMenu: String { v[36] }
    var first: String { v[37] }
    var last: String { v[38] }

    private static let count = 39

    static func `for`(_ code: String) -> Strings {
        let row = table[code] ?? []
        return Strings(v: row.count == count ? row : table["en"]!)
    }

    /// The app's language: the first of the system's preferred languages that the bundle has
    /// (build.sh makes an .lproj for each row here), so a per-app language from System
    /// Settings → General → Language & Region counts too.
    static let code: String = {
        if let first = Bundle.main.preferredLocalizations.first, table[first] != nil { return first }
        for id in Locale.preferredLanguages {
            if table[id] != nil { return id }
            let lang = Locale.Language(identifier: id)
            guard let code = lang.languageCode?.identifier else { continue }
            if code == "zh" {
                let hant = lang.script?.identifier == "Hant" || ["TW", "HK", "MO"].contains(lang.region?.identifier ?? "")
                return hant ? "zh-Hant" : "zh-Hans"
            }
            if code == "no" || code == "nn" { return "nb" }
            if table[code] != nil { return code }
        }
        return "en"
    }()

    static let current = Strings.for(code)
    static let rtl = ["ar", "he", "fa"].contains(code)

    static let table: [String: [String]] = [
        "pl": ["Otwórz…", "Wklej ze schowka", "Upuść tutaj plik CSV, TXT lub TSV", "Dwie kolumny oddzielone przecinkiem lub średnikiem: pytanie i odpowiedź. Wzory rysują się same. Pliki zostają na Twoim Macu.", "Talie", "Schowek", "Usuń z listy", "Pokaż w Finderze", "Nie znaleziono fiszek. Plik musi mieć dwie kolumny: pytanie i odpowiedź.", "Nie można odczytać pliku.", "Pytanie", "Odpowiedź", "Kliknij, żeby zobaczyć odpowiedź", "Kliknij, żeby zobaczyć pytanie", "Nie umiem", "Umiem", "Losuj", "Resetuj postęp", "Resetować postęp?", "Wszystkie oceny zostaną usunięte. Karty pozostaną.", "Resetuj", "Anuluj", "Koniec talii!", "Wszystkich", "Powtórz nieumiane", "Powtórz wszystkie", "Znasz wszystkie fiszki!", "Nie przejmuj się — powtórz jeszcze raz!", "Powtórz nieumiane, żeby je opanować.", "Bez oceny: %d", "Odsłuchaj", "Odwróć kartę", "Poprzednia karta", "Następna karta", "Talia", "Otwórz ostatnie", "Wyczyść menu", "Pierwsza karta", "Ostatnia karta"],
        "en": ["Open…", "Paste from Clipboard", "Drop a CSV, TXT or TSV file here", "Two columns separated by a comma or semicolon: question and answer. Formulas are drawn automatically. Files stay on your Mac.", "Decks", "Clipboard", "Remove from List", "Show in Finder", "No flashcards found. The file needs two columns: question and answer.", "The file can’t be read.", "Question", "Answer", "Click to see the answer", "Click to see the question", "Don’t Know", "Got It", "Shuffle", "Reset Progress", "Reset progress?", "All ratings will be removed. The cards stay.", "Reset", "Cancel", "End of the deck!", "All", "Retry Missed", "Retry All", "You know them all!", "Don’t worry — go through them again!", "Retry the missed ones to master them.", "Not rated: %d", "Listen", "Flip Card", "Previous Card", "Next Card", "Deck", "Open Recent", "Clear Menu", "First Card", "Last Card"],
        "de": ["Öffnen …", "Aus Zwischenablage einsetzen", "CSV-, TXT- oder TSV-Datei hier ablegen", "Zwei Spalten, getrennt durch Komma oder Semikolon: Frage und Antwort. Formeln werden automatisch gesetzt. Dateien bleiben auf deinem Mac.", "Stapel", "Zwischenablage", "Aus Liste entfernen", "Im Finder anzeigen", "Keine Karteikarten gefunden. Die Datei braucht zwei Spalten: Frage und Antwort.", "Die Datei kann nicht gelesen werden.", "Frage", "Antwort", "Klicke, um die Antwort zu sehen", "Klicke, um die Frage zu sehen", "Weiß ich nicht", "Weiß ich", "Mischen", "Fortschritt zurücksetzen", "Fortschritt zurücksetzen?", "Alle Bewertungen werden entfernt. Die Karten bleiben.", "Zurücksetzen", "Abbrechen", "Ende des Stapels!", "Alle", "Nicht gewusste wiederholen", "Alle wiederholen", "Du kennst alle!", "Keine Sorge – geh sie noch einmal durch!", "Wiederhole die nicht gewussten, um sie zu lernen.", "Ohne Bewertung: %d", "Anhören", "Karte umdrehen", "Vorherige Karte", "Nächste Karte", "Stapel", "Benutzte Dokumente", "Einträge löschen", "Erste Karte", "Letzte Karte"],
        "fr": ["Ouvrir…", "Coller depuis le presse-papiers", "Déposez ici un fichier CSV, TXT ou TSV", "Deux colonnes séparées par une virgule ou un point-virgule : question et réponse. Les formules sont rendues automatiquement. Les fichiers restent sur votre Mac.", "Paquets", "Presse-papiers", "Retirer de la liste", "Afficher dans le Finder", "Aucune carte trouvée. Le fichier doit avoir deux colonnes : question et réponse.", "Impossible de lire le fichier.", "Question", "Réponse", "Cliquez pour voir la réponse", "Cliquez pour voir la question", "Je ne sais pas", "Je sais", "Mélanger", "Réinitialiser la progression", "Réinitialiser la progression ?", "Toutes les évaluations seront supprimées. Les cartes restent.", "Réinitialiser", "Annuler", "Fin du paquet !", "Toutes", "Revoir les ratées", "Tout revoir", "Vous les connaissez toutes !", "Pas de souci — repassez-les encore une fois !", "Revoyez celles que vous ne saviez pas pour les maîtriser.", "Sans évaluation : %d", "Écouter", "Retourner la carte", "Carte précédente", "Carte suivante", "Paquet", "Ouvrir l’élément récent", "Effacer le menu", "Première carte", "Dernière carte"],
        "es": ["Abrir…", "Pegar del portapapeles", "Suelta aquí un archivo CSV, TXT o TSV", "Dos columnas separadas por coma o punto y coma: pregunta y respuesta. Las fórmulas se dibujan automáticamente. Los archivos se quedan en tu Mac.", "Mazos", "Portapapeles", "Eliminar de la lista", "Mostrar en Finder", "No se encontraron tarjetas. El archivo necesita dos columnas: pregunta y respuesta.", "No se puede leer el archivo.", "Pregunta", "Respuesta", "Haz clic para ver la respuesta", "Haz clic para ver la pregunta", "No lo sé", "Lo sé", "Aleatorio", "Restablecer progreso", "¿Restablecer el progreso?", "Se eliminarán todas las valoraciones. Las tarjetas se quedan.", "Restablecer", "Cancelar", "¡Fin del mazo!", "Todas", "Repetir las falladas", "Repetir todas", "¡Te las sabes todas!", "No te preocupes: ¡repásalas otra vez!", "Repite las que no sabías para dominarlas.", "Sin valorar: %d", "Escuchar", "Girar tarjeta", "Tarjeta anterior", "Tarjeta siguiente", "Mazo", "Abrir recientes", "Vaciar menú", "Primera tarjeta", "Última tarjeta"],
        "pt": ["Abrir…", "Colar da área de transferência", "Largue aqui um ficheiro CSV, TXT ou TSV", "Duas colunas separadas por vírgula ou ponto e vírgula: pergunta e resposta. As fórmulas são desenhadas automaticamente. Os ficheiros ficam no seu Mac.", "Baralhos", "Área de transferência", "Remover da lista", "Mostrar no Finder", "Nenhum cartão encontrado. O ficheiro precisa de duas colunas: pergunta e resposta.", "Não é possível ler o ficheiro.", "Pergunta", "Resposta", "Clique para ver a resposta", "Clique para ver a pergunta", "Não sei", "Sei", "Aleatório", "Repor progresso", "Repor o progresso?", "Todas as avaliações serão removidas. Os cartões ficam.", "Repor", "Cancelar", "Fim do baralho!", "Todos", "Repetir os falhados", "Repetir todos", "Sabe-os todos!", "Não se preocupe — reveja-os outra vez!", "Repita os que não sabia para os dominar.", "Sem avaliação: %d", "Ouvir", "Virar cartão", "Cartão anterior", "Cartão seguinte", "Baralho", "Abrir documento recente", "Limpar menu", "Primeiro cartão", "Último cartão"],
        "it": ["Apri…", "Incolla dagli appunti", "Trascina qui un file CSV, TXT o TSV", "Due colonne separate da virgola o punto e virgola: domanda e risposta. Le formule vengono disegnate automaticamente. I file restano sul tuo Mac.", "Mazzi", "Appunti", "Rimuovi dall’elenco", "Mostra nel Finder", "Nessuna flashcard trovata. Il file deve avere due colonne: domanda e risposta.", "Impossibile leggere il file.", "Domanda", "Risposta", "Fai clic per vedere la risposta", "Fai clic per vedere la domanda", "Non lo so", "Lo so", "Casuale", "Azzera progressi", "Azzerare i progressi?", "Tutte le valutazioni verranno rimosse. Le carte restano.", "Azzera", "Annulla", "Fine del mazzo!", "Tutte", "Ripeti le sbagliate", "Ripeti tutte", "Le sai tutte!", "Non preoccuparti: ripassale ancora!", "Ripeti quelle che non sapevi per impararle.", "Senza valutazione: %d", "Ascolta", "Gira la carta", "Carta precedente", "Carta successiva", "Mazzo", "Apri recenti", "Cancella menu", "Prima carta", "Ultima carta"],
        "nl": ["Open…", "Plak vanaf klembord", "Sleep hier een CSV-, TXT- of TSV-bestand naartoe", "Twee kolommen gescheiden door een komma of puntkomma: vraag en antwoord. Formules worden automatisch weergegeven. Bestanden blijven op je Mac.", "Stapels", "Klembord", "Verwijder uit lijst", "Toon in Finder", "Geen kaarten gevonden. Het bestand moet twee kolommen hebben: vraag en antwoord.", "Het bestand kan niet worden gelezen.", "Vraag", "Antwoord", "Klik om het antwoord te zien", "Klik om de vraag te zien", "Weet ik niet", "Weet ik", "Shuffle", "Herstel voortgang", "Voortgang herstellen?", "Alle beoordelingen worden verwijderd. De kaarten blijven.", "Herstel", "Annuleer", "Einde van de stapel!", "Alle", "Herhaal gemiste", "Herhaal alle", "Je kent ze allemaal!", "Geen zorgen – loop ze nog eens door!", "Herhaal de kaarten die je niet wist om ze te leren.", "Niet beoordeeld: %d", "Luister", "Draai kaart om", "Vorige kaart", "Volgende kaart", "Stapel", "Open recente bestanden", "Wis menu", "Eerste kaart", "Laatste kaart"],
        "sv": ["Öppna…", "Klistra in från urklipp", "Släpp en CSV-, TXT- eller TSV-fil här", "Två kolumner åtskilda med komma eller semikolon: fråga och svar. Formler ritas automatiskt. Filerna stannar på din Mac.", "Kortlekar", "Urklipp", "Ta bort från listan", "Visa i Finder", "Inga kort hittades. Filen behöver två kolumner: fråga och svar.", "Filen kan inte läsas.", "Fråga", "Svar", "Klicka för att se svaret", "Klicka för att se frågan", "Kan inte", "Kan", "Blanda", "Nollställ framsteg", "Nollställa framsteg?", "Alla bedömningar tas bort. Korten finns kvar.", "Nollställ", "Avbryt", "Slut på kortleken!", "Alla", "Repetera missade", "Repetera alla", "Du kan alla!", "Ingen fara – gå igenom dem igen!", "Repetera de du inte kunde för att lära dig dem.", "Utan bedömning: %d", "Lyssna", "Vänd kortet", "Föregående kort", "Nästa kort", "Kortlek", "Öppna senaste", "Rensa menyn", "Första kortet", "Sista kortet"],
        "da": ["Åbn…", "Indsæt fra udklipsholder", "Slip en CSV-, TXT- eller TSV-fil her", "To kolonner adskilt af komma eller semikolon: spørgsmål og svar. Formler tegnes automatisk. Filerne bliver på din Mac.", "Bunker", "Udklipsholder", "Fjern fra listen", "Vis i Finder", "Ingen kort fundet. Filen skal have to kolonner: spørgsmål og svar.", "Filen kan ikke læses.", "Spørgsmål", "Svar", "Klik for at se svaret", "Klik for at se spørgsmålet", "Kan ikke", "Kan", "Bland", "Nulstil fremskridt", "Nulstil fremskridt?", "Alle vurderinger fjernes. Kortene bliver.", "Nulstil", "Annuller", "Slut på bunken!", "Alle", "Gentag missede", "Gentag alle", "Du kan dem alle!", "Bare rolig – gå dem igennem igen!", "Gentag dem, du ikke kunne, for at lære dem.", "Uden vurdering: %d", "Lyt", "Vend kort", "Forrige kort", "Næste kort", "Bunke", "Åbn seneste", "Ryd menu", "Første kort", "Sidste kort"],
        "nb": ["Åpne…", "Lim inn fra utklippstavlen", "Slipp en CSV-, TXT- eller TSV-fil her", "To kolonner skilt med komma eller semikolon: spørsmål og svar. Formler tegnes automatisk. Filene blir på Macen din.", "Kortstokker", "Utklippstavle", "Fjern fra listen", "Vis i Finder", "Fant ingen kort. Filen trenger to kolonner: spørsmål og svar.", "Filen kan ikke leses.", "Spørsmål", "Svar", "Klikk for å se svaret", "Klikk for å se spørsmålet", "Kan ikke", "Kan", "Stokk", "Nullstill fremgang", "Nullstille fremgang?", "Alle vurderinger fjernes. Kortene blir.", "Nullstill", "Avbryt", "Slutt på kortstokken!", "Alle", "Gjenta bommede", "Gjenta alle", "Du kan alle!", "Ingen fare – gå gjennom dem igjen!", "Gjenta de du ikke kunne for å lære dem.", "Uten vurdering: %d", "Lytt", "Snu kortet", "Forrige kort", "Neste kort", "Kortstokk", "Åpne sist brukte", "Tøm meny", "Første kort", "Siste kort"],
        "fi": ["Avaa…", "Sijoita leikepöydältä", "Pudota CSV-, TXT- tai TSV-tiedosto tähän", "Kaksi saraketta pilkulla tai puolipisteellä erotettuna: kysymys ja vastaus. Kaavat piirretään automaattisesti. Tiedostot pysyvät Macillasi.", "Pakat", "Leikepöytä", "Poista listalta", "Näytä Finderissa", "Kortteja ei löytynyt. Tiedostossa pitää olla kaksi saraketta: kysymys ja vastaus.", "Tiedostoa ei voi lukea.", "Kysymys", "Vastaus", "Näe vastaus klikkaamalla", "Näe kysymys klikkaamalla", "En osaa", "Osaan", "Sekoita", "Nollaa edistyminen", "Nollataanko edistyminen?", "Kaikki arviot poistetaan. Kortit säilyvät.", "Nollaa", "Kumoa", "Pakka loppui!", "Kaikki", "Kertaa väärät", "Kertaa kaikki", "Osaat kaikki!", "Ei hätää – käy ne läpi uudelleen!", "Kertaa ne, joita et osannut, niin opit ne.", "Arvioimatta: %d", "Kuuntele", "Käännä kortti", "Edellinen kortti", "Seuraava kortti", "Pakka", "Avaa äskeinen", "Tyhjennä valikko", "Ensimmäinen kortti", "Viimeinen kortti"],
        "is": ["Opna…", "Líma af klippiborði", "Slepptu CSV-, TXT- eða TSV-skrá hér", "Tveir dálkar aðskildir með kommu eða semíkommu: spurning og svar. Formúlur eru teiknaðar sjálfkrafa. Skrárnar haldast á Mac-tölvunni þinni.", "Bunkar", "Klippiborð", "Fjarlægja af lista", "Sýna í Finder", "Engin spjöld fundust. Skráin þarf tvo dálka: spurningu og svar.", "Ekki er hægt að lesa skrána.", "Spurning", "Svar", "Smelltu til að sjá svarið", "Smelltu til að sjá spurninguna", "Kann ekki", "Kann", "Stokka", "Endurstilla framvindu", "Endurstilla framvindu?", "Öll möt verða fjarlægð. Spjöldin haldast.", "Endurstilla", "Hætta við", "Bunkinn er búinn!", "Öll", "Endurtaka röng", "Endurtaka öll", "Þú kannt þau öll!", "Engar áhyggjur – farðu aftur yfir þau!", "Endurtaktu þau sem þú kunnir ekki til að læra þau.", "Ómetin: %d", "Hlusta", "Snúa spjaldi", "Fyrra spjald", "Næsta spjald", "Bunki", "Opna nýlegt", "Hreinsa valmynd", "Fyrsta spjald", "Síðasta spjald"],
        "cs": ["Otevřít…", "Vložit ze schránky", "Přetáhněte sem soubor CSV, TXT nebo TSV", "Dva sloupce oddělené čárkou nebo středníkem: otázka a odpověď. Vzorce se vykreslí automaticky. Soubory zůstávají na vašem Macu.", "Balíčky", "Schránka", "Odstranit ze seznamu", "Zobrazit ve Finderu", "Nenalezeny žádné kartičky. Soubor potřebuje dva sloupce: otázku a odpověď.", "Soubor nelze přečíst.", "Otázka", "Odpověď", "Klikněte pro zobrazení odpovědi", "Klikněte pro zobrazení otázky", "Nevím", "Vím", "Zamíchat", "Vynulovat postup", "Vynulovat postup?", "Všechna hodnocení budou odstraněna. Kartičky zůstanou.", "Vynulovat", "Zrušit", "Konec balíčku!", "Všechny", "Zopakovat neznámé", "Zopakovat vše", "Znáte je všechny!", "Nevadí – projděte je znovu!", "Zopakujte ty, které jste nevěděli, a naučíte se je.", "Bez hodnocení: %d", "Poslechnout", "Otočit kartičku", "Předchozí kartička", "Další kartička", "Balíček", "Poslední položky", "Vyprázdnit nabídku", "První kartička", "Poslední kartička"],
        "sk": ["Otvoriť…", "Vložiť zo schránky", "Pretiahnite sem súbor CSV, TXT alebo TSV", "Dva stĺpce oddelené čiarkou alebo bodkočiarkou: otázka a odpoveď. Vzorce sa vykreslia automaticky. Súbory zostávajú na vašom Macu.", "Balíčky", "Schránka", "Odstrániť zo zoznamu", "Zobraziť vo Finderi", "Nenašli sa žiadne kartičky. Súbor potrebuje dva stĺpce: otázku a odpoveď.", "Súbor sa nedá prečítať.", "Otázka", "Odpoveď", "Kliknutím zobrazíte odpoveď", "Kliknutím zobrazíte otázku", "Neviem", "Viem", "Zamiešať", "Vynulovať postup", "Vynulovať postup?", "Všetky hodnotenia sa odstránia. Kartičky zostanú.", "Vynulovať", "Zrušiť", "Koniec balíčka!", "Všetky", "Zopakovať neznáme", "Zopakovať všetky", "Viete ich všetky!", "Nevadí – prejdite ich znova!", "Zopakujte tie, ktoré ste nevedeli, a naučíte sa ich.", "Bez hodnotenia: %d", "Vypočuť", "Otočiť kartičku", "Predchádzajúca kartička", "Ďalšia kartička", "Balíček", "Otvoriť posledné", "Vyčistiť menu", "Prvá kartička", "Posledná kartička"],
        "sl": ["Odpri …", "Prilepi iz odložišča", "Sem spustite datoteko CSV, TXT ali TSV", "Dva stolpca, ločena z vejico ali podpičjem: vprašanje in odgovor. Formule se izrišejo samodejno. Datoteke ostanejo na vašem Macu.", "Kompleti", "Odložišče", "Odstrani s seznama", "Pokaži v Finderju", "Ni kartic. Datoteka potrebuje dva stolpca: vprašanje in odgovor.", "Datoteke ni mogoče prebrati.", "Vprašanje", "Odgovor", "Kliknite za odgovor", "Kliknite za vprašanje", "Ne vem", "Vem", "Premešaj", "Ponastavi napredek", "Želite ponastaviti napredek?", "Vse ocene bodo odstranjene. Kartice ostanejo.", "Ponastavi", "Prekliči", "Konec kompleta!", "Vse", "Ponovi zgrešene", "Ponovi vse", "Znate jih vse!", "Nič hudega – preglejte jih še enkrat!", "Ponovite tiste, ki jih niste znali, da se jih naučite.", "Brez ocene: %d", "Poslušaj", "Obrni kartico", "Prejšnja kartica", "Naslednja kartica", "Komplet", "Odpri nedavno", "Počisti meni", "Prva kartica", "Zadnja kartica"],
        "hr": ["Otvori…", "Zalijepi iz međuspremnika", "Ovdje ispustite CSV, TXT ili TSV datoteku", "Dva stupca odvojena zarezom ili točkom sa zarezom: pitanje i odgovor. Formule se iscrtavaju automatski. Datoteke ostaju na vašem Macu.", "Špilovi", "Međuspremnik", "Ukloni s popisa", "Prikaži u Finderu", "Nisu pronađene kartice. Datoteka treba dva stupca: pitanje i odgovor.", "Datoteku nije moguće pročitati.", "Pitanje", "Odgovor", "Kliknite za odgovor", "Kliknite za pitanje", "Ne znam", "Znam", "Promiješaj", "Resetiraj napredak", "Resetirati napredak?", "Sve ocjene bit će uklonjene. Kartice ostaju.", "Resetiraj", "Odustani", "Kraj špila!", "Sve", "Ponovi promašene", "Ponovi sve", "Znate ih sve!", "Bez brige – prođite ih ponovno!", "Ponovite one koje niste znali da ih naučite.", "Bez ocjene: %d", "Poslušaj", "Okreni karticu", "Prethodna kartica", "Sljedeća kartica", "Špil", "Otvori nedavne stavke", "Očisti izbornik", "Prva kartica", "Zadnja kartica"],
        "sr": ["Отвори…", "Налепи из оставе", "Превуците овде CSV, TXT или TSV датотеку", "Две колоне одвојене зарезом или тачком и зарезом: питање и одговор. Формуле се исцртавају аутоматски. Датотеке остају на вашем Mac рачунару.", "Шпилови", "Остава", "Уклони са листе", "Прикажи у Finder-у", "Нису пронађене картице. Датотека треба да има две колоне: питање и одговор.", "Датотека не може да се прочита.", "Питање", "Одговор", "Кликните да видите одговор", "Кликните да видите питање", "Не знам", "Знам", "Промешај", "Ресетуј напредак", "Ресетовати напредак?", "Све оцене ће бити уклоњене. Картице остају.", "Ресетуј", "Одустани", "Крај шпила!", "Све", "Понови промашене", "Понови све", "Знате их све!", "Без бриге – прођите их поново!", "Поновите оне које нисте знали да их научите.", "Без оцене: %d", "Слушај", "Окрени картицу", "Претходна картица", "Следећа картица", "Шпил", "Отвори недавно", "Очисти мени", "Прва картица", "Последња картица"],
        "bg": ["Отвори…", "Постави от клипборда", "Пуснете тук CSV, TXT или TSV файл", "Две колони, разделени със запетая или точка и запетая: въпрос и отговор. Формулите се изобразяват автоматично. Файловете остават на вашия Mac.", "Тестета", "Клипборд", "Премахни от списъка", "Покажи във Finder", "Няма намерени карти. Файлът трябва да има две колони: въпрос и отговор.", "Файлът не може да бъде прочетен.", "Въпрос", "Отговор", "Щракнете, за да видите отговора", "Щракнете, за да видите въпроса", "Не знам", "Знам", "Разбъркай", "Нулирай напредъка", "Да се нулира ли напредъкът?", "Всички оценки ще бъдат премахнати. Картите остават.", "Нулирай", "Отказ", "Край на тестето!", "Всички", "Повтори пропуснатите", "Повтори всички", "Знаете ги всички!", "Не се притеснявайте – минете ги отново!", "Повторете тези, които не знаехте, за да ги научите.", "Без оценка: %d", "Слушай", "Обърни картата", "Предишна карта", "Следваща карта", "Тесте", "Отвори скорошни", "Изчисти менюто", "Първа карта", "Последна карта"],
        "ro": ["Deschideți…", "Lipiți din clipboard", "Plasați aici un fișier CSV, TXT sau TSV", "Două coloane separate prin virgulă sau punct și virgulă: întrebare și răspuns. Formulele sunt desenate automat. Fișierele rămân pe Mac-ul dvs.", "Pachete", "Clipboard", "Eliminați din listă", "Afișați în Finder", "Nu s-au găsit fișe. Fișierul are nevoie de două coloane: întrebare și răspuns.", "Fișierul nu poate fi citit.", "Întrebare", "Răspuns", "Faceți clic pentru a vedea răspunsul", "Faceți clic pentru a vedea întrebarea", "Nu știu", "Știu", "Amestecare", "Resetați progresul", "Resetați progresul?", "Toate evaluările vor fi eliminate. Fișele rămân.", "Resetați", "Anulați", "Sfârșitul pachetului!", "Toate", "Repetați greșitele", "Repetați toate", "Le știți pe toate!", "Nicio grijă – parcurgeți-le din nou!", "Repetați-le pe cele pe care nu le-ați știut ca să le învățați.", "Neevaluate: %d", "Ascultați", "Întoarceți fișa", "Fișa anterioară", "Fișa următoare", "Pachet", "Deschideți recente", "Degajați meniul", "Prima fișă", "Ultima fișă"],
        "hu": ["Megnyitás…", "Beillesztés vágólapról", "Húzzon ide egy CSV-, TXT- vagy TSV-fájlt", "Két oszlop vesszővel vagy pontosvesszővel elválasztva: kérdés és válasz. A képletek automatikusan megjelennek. A fájlok a Macen maradnak.", "Paklik", "Vágólap", "Eltávolítás a listából", "Megjelenítés a Finderben", "Nem található kártya. A fájlnak két oszlop kell: kérdés és válasz.", "A fájl nem olvasható.", "Kérdés", "Válasz", "Kattintson a válaszhoz", "Kattintson a kérdéshez", "Nem tudom", "Tudom", "Keverés", "Haladás visszaállítása", "Visszaállítja a haladást?", "Minden értékelés törlődik. A kártyák megmaradnak.", "Visszaállítás", "Mégsem", "Vége a paklinak!", "Összes", "Hibásak ismétlése", "Összes ismétlése", "Mindet tudja!", "Semmi gond – nézze át őket újra!", "Ismételje a nem tudottakat, hogy megtanulja őket.", "Értékelés nélkül: %d", "Meghallgatás", "Kártya megfordítása", "Előző kártya", "Következő kártya", "Pakli", "Legutóbbi megnyitása", "Menü törlése", "Első kártya", "Utolsó kártya"],
        "el": ["Άνοιγμα…", "Επικόλληση από το πρόχειρο", "Αποθέστε εδώ ένα αρχείο CSV, TXT ή TSV", "Δύο στήλες χωρισμένες με κόμμα ή ερωτηματικό: ερώτηση και απάντηση. Οι τύποι σχεδιάζονται αυτόματα. Τα αρχεία μένουν στο Mac σας.", "Τράπουλες", "Πρόχειρο", "Αφαίρεση από τη λίστα", "Εμφάνιση στο Finder", "Δεν βρέθηκαν κάρτες. Το αρχείο χρειάζεται δύο στήλες: ερώτηση και απάντηση.", "Δεν είναι δυνατή η ανάγνωση του αρχείου.", "Ερώτηση", "Απάντηση", "Κάντε κλικ για την απάντηση", "Κάντε κλικ για την ερώτηση", "Δεν ξέρω", "Ξέρω", "Ανακάτεμα", "Επαναφορά προόδου", "Επαναφορά προόδου;", "Όλες οι βαθμολογίες θα αφαιρεθούν. Οι κάρτες μένουν.", "Επαναφορά", "Ακύρωση", "Τέλος της τράπουλας!", "Όλες", "Επανάληψη λανθασμένων", "Επανάληψη όλων", "Τις ξέρετε όλες!", "Μην ανησυχείτε – περάστε τις ξανά!", "Επαναλάβετε όσες δεν ξέρατε για να τις μάθετε.", "Χωρίς βαθμολογία: %d", "Ακρόαση", "Αναστροφή κάρτας", "Προηγούμενη κάρτα", "Επόμενη κάρτα", "Τράπουλα", "Άνοιγμα πρόσφατου", "Εκκαθάριση μενού", "Πρώτη κάρτα", "Τελευταία κάρτα"],
        "tr": ["Aç…", "Panodan Yapıştır", "Buraya bir CSV, TXT veya TSV dosyası bırakın", "Virgül veya noktalı virgülle ayrılmış iki sütun: soru ve cevap. Formüller otomatik çizilir. Dosyalar Mac’inizde kalır.", "Desteler", "Pano", "Listeden Kaldır", "Finder’da Göster", "Kart bulunamadı. Dosyada iki sütun olmalı: soru ve cevap.", "Dosya okunamıyor.", "Soru", "Cevap", "Cevabı görmek için tıklayın", "Soruyu görmek için tıklayın", "Bilmiyorum", "Biliyorum", "Karıştır", "İlerlemeyi Sıfırla", "İlerleme sıfırlansın mı?", "Tüm değerlendirmeler silinecek. Kartlar kalır.", "Sıfırla", "Vazgeç", "Destenin sonu!", "Tümü", "Bilinmeyenleri Tekrarla", "Tümünü Tekrarla", "Hepsini biliyorsunuz!", "Endişelenmeyin, bir kez daha gözden geçirin!", "Öğrenmek için bilmediklerinizi tekrarlayın.", "Değerlendirilmemiş: %d", "Dinle", "Kartı Çevir", "Önceki Kart", "Sonraki Kart", "Deste", "Son Kullanılanı Aç", "Menüyü Boşalt", "İlk Kart", "Son Kart"],
        "uk": ["Відкрити…", "Вставити з буфера", "Перетягніть сюди файл CSV, TXT або TSV", "Дві колонки, розділені комою або крапкою з комою: питання і відповідь. Формули малюються автоматично. Файли лишаються на вашому Mac.", "Колоди", "Буфер обміну", "Вилучити зі списку", "Показати у Finder", "Карток не знайдено. Файл має містити дві колонки: питання і відповідь.", "Не вдається прочитати файл.", "Питання", "Відповідь", "Клацніть, щоб побачити відповідь", "Клацніть, щоб побачити питання", "Не знаю", "Знаю", "Перемішати", "Скинути прогрес", "Скинути прогрес?", "Усі оцінки буде вилучено. Картки лишаться.", "Скинути", "Скасувати", "Кінець колоди!", "Усі", "Повторити невідомі", "Повторити всі", "Ви знаєте всі!", "Не хвилюйтеся – пройдіть їх ще раз!", "Повторіть ті, яких не знали, щоб їх вивчити.", "Без оцінки: %d", "Прослухати", "Перевернути картку", "Попередня картка", "Наступна картка", "Колода", "Відкрити недавні", "Очистити меню", "Перша картка", "Остання картка"],
        "ru": ["Открыть…", "Вставить из буфера", "Перетащите сюда файл CSV, TXT или TSV", "Две колонки через запятую или точку с запятой: вопрос и ответ. Формулы рисуются автоматически. Файлы остаются на вашем Mac.", "Колоды", "Буфер обмена", "Удалить из списка", "Показать в Finder", "Карточки не найдены. В файле должно быть две колонки: вопрос и ответ.", "Не удается прочитать файл.", "Вопрос", "Ответ", "Нажмите, чтобы увидеть ответ", "Нажмите, чтобы увидеть вопрос", "Не знаю", "Знаю", "Перемешать", "Сбросить прогресс", "Сбросить прогресс?", "Все оценки будут удалены. Карточки останутся.", "Сбросить", "Отменить", "Конец колоды!", "Все", "Повторить незнакомые", "Повторить все", "Вы знаете все!", "Не переживайте — пройдите их еще раз!", "Повторите те, что не знали, чтобы выучить их.", "Без оценки: %d", "Прослушать", "Перевернуть карточку", "Предыдущая карточка", "Следующая карточка", "Колода", "Открытие недавних", "Очистить меню", "Первая карточка", "Последняя карточка"],
        "be": ["Адкрыць…", "Уставіць з буфера", "Перацягніце сюды файл CSV, TXT або TSV", "Дзве калонкі праз коску або кропку з коскай: пытанне і адказ. Формулы малююцца аўтаматычна. Файлы застаюцца на вашым Mac.", "Калоды", "Буфер абмену", "Выдаліць са спіса", "Паказаць у Finder", "Картак не знойдзена. У файле павінна быць дзве калонкі: пытанне і адказ.", "Немагчыма прачытаць файл.", "Пытанне", "Адказ", "Націсніце, каб убачыць адказ", "Націсніце, каб убачыць пытанне", "Не ведаю", "Ведаю", "Перамяшаць", "Скінуць прагрэс", "Скінуць прагрэс?", "Усе ацэнкі будуць выдалены. Карткі застануцца.", "Скінуць", "Скасаваць", "Канец калоды!", "Усе", "Паўтарыць невядомыя", "Паўтарыць усе", "Вы ведаеце ўсе!", "Не перажывайце — прайдзіце іх яшчэ раз!", "Паўтарыце тыя, што не ведалі, каб іх вывучыць.", "Без ацэнкі: %d", "Праслухаць", "Перавярнуць картку", "Папярэдняя картка", "Наступная картка", "Калода", "Адкрыць нядаўнія", "Ачысціць меню", "Першая картка", "Апошняя картка"],
        "lt": ["Atidaryti…", "Įklijuoti iš iškarpinės", "Nuvilkite čia CSV, TXT arba TSV failą", "Du stulpeliai, atskirti kableliu arba kabliataškiu: klausimas ir atsakymas. Formulės nupiešiamos automatiškai. Failai lieka jūsų „Mac“.", "Kaladės", "Iškarpinė", "Pašalinti iš sąrašo", "Rodyti „Finder“", "Kortelių nerasta. Faile turi būti du stulpeliai: klausimas ir atsakymas.", "Failo nepavyksta perskaityti.", "Klausimas", "Atsakymas", "Spustelėkite, kad pamatytumėte atsakymą", "Spustelėkite, kad pamatytumėte klausimą", "Nežinau", "Žinau", "Maišyti", "Atstatyti pažangą", "Atstatyti pažangą?", "Visi įvertinimai bus pašalinti. Kortelės liks.", "Atstatyti", "Atšaukti", "Kaladės pabaiga!", "Visos", "Kartoti nežinotas", "Kartoti visas", "Jūs žinote visas!", "Nesijaudinkite – peržiūrėkite jas dar kartą!", "Pakartokite tas, kurių nežinojote, kad jas išmoktumėte.", "Neįvertinta: %d", "Klausyti", "Apversti kortelę", "Ankstesnė kortelė", "Kita kortelė", "Kaladė", "Atidaryti naujausius", "Išvalyti meniu", "Pirma kortelė", "Paskutinė kortelė"],
        "lv": ["Atvērt…", "Ielīmēt no starpliktuves", "Nometiet šeit CSV, TXT vai TSV failu", "Divas kolonnas, atdalītas ar komatu vai semikolu: jautājums un atbilde. Formulas tiek uzzīmētas automātiski. Faili paliek jūsu Mac datorā.", "Kavas", "Starpliktuve", "Noņemt no saraksta", "Rādīt Finder", "Kartītes netika atrastas. Failā jābūt divām kolonnām: jautājums un atbilde.", "Failu nevar nolasīt.", "Jautājums", "Atbilde", "Noklikšķiniet, lai redzētu atbildi", "Noklikšķiniet, lai redzētu jautājumu", "Nezinu", "Zinu", "Sajaukt", "Atiestatīt progresu", "Atiestatīt progresu?", "Visi vērtējumi tiks noņemti. Kartītes paliks.", "Atiestatīt", "Atcelt", "Kavas beigas!", "Visas", "Atkārtot nezināmās", "Atkārtot visas", "Jūs zināt visas!", "Neuztraucieties – izejiet tām cauri vēlreiz!", "Atkārtojiet tās, ko nezinājāt, lai tās iemācītos.", "Bez vērtējuma: %d", "Klausīties", "Apgriezt kartīti", "Iepriekšējā kartīte", "Nākamā kartīte", "Kava", "Atvērt nesenos", "Notīrīt izvēlni", "Pirmā kartīte", "Pēdējā kartīte"],
        "et": ["Ava…", "Kleebi lõikelaualt", "Lohista siia CSV-, TXT- või TSV-fail", "Kaks veergu, eraldatud koma või semikooloniga: küsimus ja vastus. Valemid joonistatakse automaatselt. Failid jäävad sinu Macile.", "Pakid", "Lõikelaud", "Eemalda loendist", "Näita Finderis", "Kaarte ei leitud. Failis peab olema kaks veergu: küsimus ja vastus.", "Faili ei saa lugeda.", "Küsimus", "Vastus", "Klõpsa, et näha vastust", "Klõpsa, et näha küsimust", "Ei tea", "Tean", "Sega", "Lähtesta edenemine", "Kas lähtestada edenemine?", "Kõik hinnangud eemaldatakse. Kaardid jäävad.", "Lähtesta", "Tühista", "Pakk on läbi!", "Kõik", "Korda valesid", "Korda kõiki", "Sa tead kõiki!", "Ära muretse – käi need uuesti läbi!", "Korda neid, mida ei teadnud, et need selgeks saada.", "Hindamata: %d", "Kuula", "Pööra kaart", "Eelmine kaart", "Järgmine kaart", "Pakk", "Ava hiljutised", "Tühjenda menüü", "Esimene kaart", "Viimane kaart"],
        "ca": ["Obre…", "Enganxa del porta-retalls", "Deixa anar aquí un fitxer CSV, TXT o TSV", "Dues columnes separades per coma o punt i coma: pregunta i resposta. Les fórmules es dibuixen automàticament. Els fitxers es queden al Mac.", "Piles", "Porta-retalls", "Elimina de la llista", "Mostra al Finder", "No s’han trobat targetes. El fitxer necessita dues columnes: pregunta i resposta.", "No es pot llegir el fitxer.", "Pregunta", "Resposta", "Fes clic per veure la resposta", "Fes clic per veure la pregunta", "No ho sé", "Ho sé", "Aleatori", "Restableix el progrés", "Vols restablir el progrés?", "S’eliminaran totes les valoracions. Les targetes es queden.", "Restableix", "Cancel·la", "Fi de la pila!", "Totes", "Repeteix les fallades", "Repeteix-les totes", "Te les saps totes!", "No pateixis: repassa-les un altre cop!", "Repeteix les que no sabies per dominar-les.", "Sense valorar: %d", "Escolta", "Gira la targeta", "Targeta anterior", "Targeta següent", "Pila", "Obre els recents", "Buida el menú", "Primera targeta", "Última targeta"],
        "ar": ["فتح…", "لصق من الحافظة", "أفلت ملف CSV أو TXT أو TSV هنا", "عمودان مفصولان بفاصلة أو فاصلة منقوطة: السؤال والإجابة. تُرسم الصيغ تلقائيًا. تبقى الملفات على جهاز Mac.", "المجموعات", "الحافظة", "إزالة من القائمة", "إظهار في Finder", "لم يتم العثور على بطاقات. يحتاج الملف إلى عمودين: السؤال والإجابة.", "تعذرت قراءة الملف.", "سؤال", "إجابة", "انقر لرؤية الإجابة", "انقر لرؤية السؤال", "لا أعرف", "أعرف", "خلط", "إعادة تعيين التقدم", "هل تريد إعادة تعيين التقدم؟", "ستتم إزالة جميع التقييمات. ستبقى البطاقات.", "إعادة تعيين", "إلغاء", "نهاية المجموعة!", "الكل", "إعادة ما أخطأت فيه", "إعادة الكل", "أنت تعرفها كلها!", "لا تقلق — راجعها مرة أخرى!", "أعد ما لم تعرفه لتتقنه.", "بدون تقييم: %d", "استماع", "قلب البطاقة", "البطاقة السابقة", "البطاقة التالية", "المجموعة", "فتح العناصر الأخيرة", "مسح القائمة", "البطاقة الأولى", "البطاقة الأخيرة"],
        "he": ["פתיחה…", "הדבקה מהלוח", "יש לשחרר כאן קובץ CSV,‏ TXT או TSV", "שתי עמודות מופרדות בפסיק או בנקודה-פסיק: שאלה ותשובה. נוסחאות מצוירות אוטומטית. הקבצים נשארים ב‑Mac שלך.", "חפיסות", "לוח", "הסרה מהרשימה", "הצגה ב‑Finder", "לא נמצאו כרטיסיות. הקובץ צריך שתי עמודות: שאלה ותשובה.", "לא ניתן לקרוא את הקובץ.", "שאלה", "תשובה", "יש ללחוץ כדי לראות את התשובה", "יש ללחוץ כדי לראות את השאלה", "לא יודע/ת", "יודע/ת", "ערבוב", "איפוס ההתקדמות", "לאפס את ההתקדמות?", "כל הדירוגים יוסרו. הכרטיסיות נשארות.", "איפוס", "ביטול", "סוף החפיסה!", "הכול", "חזרה על השגויות", "חזרה על הכול", "את/ה יודע/ת את כולן!", "לא נורא — עבור/י עליהן שוב!", "חזור/י על אלה שלא ידעת כדי ללמוד אותן.", "ללא דירוג: %d", "האזנה", "הפיכת הכרטיסייה", "הכרטיסייה הקודמת", "הכרטיסייה הבאה", "חפיסה", "פתיחת האחרונים", "ניקוי התפריט", "הכרטיסייה הראשונה", "הכרטיסייה האחרונה"],
        "fa": ["باز کردن…", "چسباندن از کلیپ‌بورد", "یک فایل CSV، TXT یا TSV را اینجا رها کنید", "دو ستون جداشده با ویرگول یا نقطه‌ویرگول: پرسش و پاسخ. فرمول‌ها خودکار رسم می‌شوند. فایل‌ها روی Mac شما می‌مانند.", "دسته‌ها", "کلیپ‌بورد", "حذف از فهرست", "نمایش در Finder", "کارتی پیدا نشد. فایل باید دو ستون داشته باشد: پرسش و پاسخ.", "فایل خوانده نمی‌شود.", "پرسش", "پاسخ", "برای دیدن پاسخ کلیک کنید", "برای دیدن پرسش کلیک کنید", "نمی‌دانم", "می‌دانم", "بُر زدن", "بازنشانی پیشرفت", "پیشرفت بازنشانی شود؟", "همهٔ ارزیابی‌ها حذف می‌شوند. کارت‌ها می‌مانند.", "بازنشانی", "لغو", "پایان دسته!", "همه", "تکرار نادانسته‌ها", "تکرار همه", "همه را می‌دانید!", "نگران نباشید — دوباره مرورشان کنید!", "آن‌هایی را که نمی‌دانستید تکرار کنید تا یادشان بگیرید.", "بدون ارزیابی: %d", "گوش دادن", "برگرداندن کارت", "کارت قبلی", "کارت بعدی", "دسته", "باز کردن موارد اخیر", "پاک کردن منو", "کارت اول", "کارت آخر"],
        "hi": ["खोलें…", "क्लिपबोर्ड से पेस्ट करें", "यहाँ CSV, TXT या TSV फ़ाइल छोड़ें", "अल्पविराम या अर्धविराम से अलग दो कॉलम: प्रश्न और उत्तर। सूत्र अपने आप बनते हैं। फ़ाइलें आपके Mac पर ही रहती हैं।", "डेक", "क्लिपबोर्ड", "सूची से हटाएँ", "Finder में दिखाएँ", "कोई फ़्लैशकार्ड नहीं मिला। फ़ाइल में दो कॉलम होने चाहिए: प्रश्न और उत्तर।", "फ़ाइल पढ़ी नहीं जा सकती।", "प्रश्न", "उत्तर", "उत्तर देखने के लिए क्लिक करें", "प्रश्न देखने के लिए क्लिक करें", "नहीं आता", "आता है", "शफ़ल", "प्रगति रीसेट करें", "प्रगति रीसेट करें?", "सभी रेटिंग हटा दी जाएँगी। कार्ड बने रहेंगे।", "रीसेट करें", "रद्द करें", "डेक खत्म!", "सभी", "छूटे हुए दोहराएँ", "सभी दोहराएँ", "आपको सब आते हैं!", "चिंता न करें — इन्हें फिर से देखें!", "जो नहीं आते थे उन्हें दोहराएँ ताकि वे याद हो जाएँ।", "बिना रेटिंग: %d", "सुनें", "कार्ड पलटें", "पिछला कार्ड", "अगला कार्ड", "डेक", "हालिया खोलें", "मेन्यू साफ़ करें", "पहला कार्ड", "अंतिम कार्ड"],
        "bn": ["খুলুন…", "ক্লিপবোর্ড থেকে পেস্ট করুন", "এখানে একটি CSV, TXT বা TSV ফাইল ছাড়ুন", "কমা বা সেমিকোলন দিয়ে আলাদা দুটি কলাম: প্রশ্ন ও উত্তর। সূত্র নিজে থেকেই আঁকা হয়। ফাইল আপনার Mac-এই থাকে।", "ডেক", "ক্লিপবোর্ড", "তালিকা থেকে সরান", "Finder-এ দেখান", "কোনো ফ্ল্যাশকার্ড পাওয়া যায়নি। ফাইলে দুটি কলাম লাগবে: প্রশ্ন ও উত্তর।", "ফাইলটি পড়া যাচ্ছে না।", "প্রশ্ন", "উত্তর", "উত্তর দেখতে ক্লিক করুন", "প্রশ্ন দেখতে ক্লিক করুন", "জানি না", "জানি", "এলোমেলো", "অগ্রগতি রিসেট করুন", "অগ্রগতি রিসেট করবেন?", "সব রেটিং মুছে যাবে। কার্ডগুলো থাকবে।", "রিসেট", "বাতিল", "ডেক শেষ!", "সব", "ভুলগুলো আবার করুন", "সব আবার করুন", "আপনি সবগুলো জানেন!", "চিন্তা নেই — আবার দেখে নিন!", "যেগুলো জানতেন না সেগুলো আবার করুন, শিখে যাবেন।", "রেটিং ছাড়া: %d", "শুনুন", "কার্ড উল্টান", "আগের কার্ড", "পরের কার্ড", "ডেক", "সাম্প্রতিক খুলুন", "মেনু পরিষ্কার করুন", "প্রথম কার্ড", "শেষ কার্ড"],
        "th": ["เปิด…", "วางจากคลิปบอร์ด", "วางไฟล์ CSV, TXT หรือ TSV ที่นี่", "สองคอลัมน์คั่นด้วยจุลภาคหรืออัฒภาค: คำถามและคำตอบ สูตรจะถูกวาดโดยอัตโนมัติ ไฟล์จะอยู่บน Mac ของคุณ", "สำรับ", "คลิปบอร์ด", "เอาออกจากรายการ", "แสดงใน Finder", "ไม่พบแฟลชการ์ด ไฟล์ต้องมีสองคอลัมน์: คำถามและคำตอบ", "ไม่สามารถอ่านไฟล์ได้", "คำถาม", "คำตอบ", "คลิกเพื่อดูคำตอบ", "คลิกเพื่อดูคำถาม", "ไม่รู้", "รู้แล้ว", "สุ่ม", "รีเซ็ตความคืบหน้า", "รีเซ็ตความคืบหน้าหรือไม่", "การให้คะแนนทั้งหมดจะถูกลบ การ์ดยังคงอยู่", "รีเซ็ต", "ยกเลิก", "จบสำรับแล้ว!", "ทั้งหมด", "ทวนข้อที่พลาด", "ทวนทั้งหมด", "คุณรู้ทั้งหมด!", "ไม่เป็นไร ลองทวนอีกครั้ง!", "ทวนข้อที่ยังไม่รู้เพื่อให้จำได้", "ยังไม่ให้คะแนน: %d", "ฟัง", "พลิกการ์ด", "การ์ดก่อนหน้า", "การ์ดถัดไป", "สำรับ", "เปิดล่าสุด", "ล้างเมนู", "การ์ดแรก", "การ์ดสุดท้าย"],
        "vi": ["Mở…", "Dán từ bảng nhớ tạm", "Thả tệp CSV, TXT hoặc TSV vào đây", "Hai cột phân tách bằng dấu phẩy hoặc dấu chấm phẩy: câu hỏi và câu trả lời. Công thức được vẽ tự động. Tệp ở lại trên máy Mac của bạn.", "Bộ thẻ", "Bảng nhớ tạm", "Xóa khỏi danh sách", "Hiển thị trong Finder", "Không tìm thấy thẻ. Tệp cần hai cột: câu hỏi và câu trả lời.", "Không thể đọc tệp.", "Câu hỏi", "Câu trả lời", "Bấm để xem câu trả lời", "Bấm để xem câu hỏi", "Chưa biết", "Đã biết", "Trộn", "Đặt lại tiến độ", "Đặt lại tiến độ?", "Tất cả đánh giá sẽ bị xóa. Thẻ vẫn còn.", "Đặt lại", "Hủy", "Hết bộ thẻ!", "Tất cả", "Ôn lại thẻ sai", "Ôn lại tất cả", "Bạn biết hết rồi!", "Đừng lo — xem lại lần nữa nhé!", "Ôn lại những thẻ chưa biết để nắm vững.", "Chưa đánh giá: %d", "Nghe", "Lật thẻ", "Thẻ trước", "Thẻ tiếp theo", "Bộ thẻ", "Mở mục gần đây", "Xóa menu", "Thẻ đầu tiên", "Thẻ cuối cùng"],
        "id": ["Buka…", "Tempel dari Papan Klip", "Letakkan file CSV, TXT, atau TSV di sini", "Dua kolom dipisahkan koma atau titik koma: pertanyaan dan jawaban. Rumus digambar otomatis. File tetap di Mac Anda.", "Dek", "Papan Klip", "Hapus dari Daftar", "Tampilkan di Finder", "Kartu tidak ditemukan. File memerlukan dua kolom: pertanyaan dan jawaban.", "File tidak dapat dibaca.", "Pertanyaan", "Jawaban", "Klik untuk melihat jawaban", "Klik untuk melihat pertanyaan", "Belum Tahu", "Tahu", "Acak", "Atur Ulang Kemajuan", "Atur ulang kemajuan?", "Semua penilaian akan dihapus. Kartu tetap ada.", "Atur Ulang", "Batalkan", "Dek selesai!", "Semua", "Ulangi yang Salah", "Ulangi Semua", "Anda tahu semuanya!", "Jangan khawatir — ulangi sekali lagi!", "Ulangi yang belum Anda tahu agar menguasainya.", "Belum dinilai: %d", "Dengarkan", "Balik Kartu", "Kartu Sebelumnya", "Kartu Berikutnya", "Dek", "Buka Terbaru", "Bersihkan Menu", "Kartu Pertama", "Kartu Terakhir"],
        "ms": ["Buka…", "Tampal daripada Papan Klip", "Lepaskan fail CSV, TXT atau TSV di sini", "Dua lajur dipisahkan koma atau koma bertitik: soalan dan jawapan. Formula dilukis secara automatik. Fail kekal di Mac anda.", "Dek", "Papan Klip", "Keluarkan daripada Senarai", "Tunjukkan dalam Finder", "Tiada kad ditemui. Fail memerlukan dua lajur: soalan dan jawapan.", "Fail tidak dapat dibaca.", "Soalan", "Jawapan", "Klik untuk melihat jawapan", "Klik untuk melihat soalan", "Tidak Tahu", "Tahu", "Kocok", "Set Semula Kemajuan", "Set semula kemajuan?", "Semua penilaian akan dikeluarkan. Kad kekal.", "Set Semula", "Batal", "Tamat dek!", "Semua", "Ulang yang Salah", "Ulang Semua", "Anda tahu semuanya!", "Jangan risau — ulang kaji sekali lagi!", "Ulang yang anda tidak tahu untuk menguasainya.", "Belum dinilai: %d", "Dengar", "Terbalikkan Kad", "Kad Sebelumnya", "Kad Seterusnya", "Dek", "Buka Terbaharu", "Kosongkan Menu", "Kad Pertama", "Kad Terakhir"],
        "zh-Hans": ["打开…", "从剪贴板粘贴", "将 CSV、TXT 或 TSV 文件拖到这里", "两列，用逗号或分号分隔：问题和答案。公式会自动绘制。文件始终留在你的 Mac 上。", "卡组", "剪贴板", "从列表中移除", "在访达中显示", "未找到抽认卡。文件需要两列：问题和答案。", "无法读取文件。", "问题", "答案", "点按以查看答案", "点按以查看问题", "不会", "会了", "随机", "重设进度", "要重设进度吗？", "所有评分将被移除。卡片会保留。", "重设", "取消", "卡组结束！", "全部", "重复不会的", "全部重复", "你全都会了！", "别担心——再过一遍！", "重复不会的卡片来掌握它们。", "未评分：%d", "朗读", "翻转卡片", "上一张卡片", "下一张卡片", "卡组", "打开最近使用", "清除菜单", "第一张卡片", "最后一张卡片"],
        "zh-Hant": ["打開⋯", "從剪貼板貼上", "將 CSV、TXT 或 TSV 檔案拖移到這裡", "兩欄，以逗號或分號分隔：問題和答案。公式會自動繪製。檔案會留在你的 Mac 上。", "卡組", "剪貼板", "從列表中移除", "在 Finder 中顯示", "找不到字卡。檔案需要兩欄：問題和答案。", "無法讀取檔案。", "問題", "答案", "按一下來查看答案", "按一下來查看問題", "不會", "會了", "隨機", "重置進度", "要重置進度嗎？", "所有評分將被移除。卡片會保留。", "重置", "取消", "卡組結束！", "全部", "重複不會的", "全部重複", "你全部都會了！", "別擔心，再複習一次！", "重複不會的卡片來掌握它們。", "未評分：%d", "朗讀", "翻轉卡片", "上一張卡片", "下一張卡片", "卡組", "打開最近使用過的檔案", "清除選單", "第一張卡片", "最後一張卡片"],
        "ja": ["開く…", "クリップボードからペースト", "CSV、TXT、TSVファイルをここにドロップ", "コンマまたはセミコロンで区切った2列：問題と答え。数式は自動で描画されます。ファイルはMacから出ません。", "デッキ", "クリップボード", "リストから削除", "Finderに表示", "カードが見つかりません。ファイルには問題と答えの2列が必要です。", "ファイルを読み込めません。", "問題", "答え", "クリックして答えを表示", "クリックして問題を表示", "わからない", "わかった", "シャッフル", "進捗をリセット", "進捗をリセットしますか？", "すべての評価が削除されます。カードは残ります。", "リセット", "キャンセル", "デッキの終わり！", "すべて", "間違えたものを復習", "すべて復習", "全部わかっています！", "大丈夫、もう一度見直しましょう！", "わからなかったカードを復習して覚えましょう。", "未評価：%d", "読み上げ", "カードを裏返す", "前のカード", "次のカード", "デッキ", "最近使った項目を開く", "メニューを消去", "最初のカード", "最後のカード"],
        "ko": ["열기…", "클립보드에서 붙여넣기", "여기에 CSV, TXT 또는 TSV 파일을 놓으십시오", "쉼표나 세미콜론으로 구분된 두 열: 질문과 답. 수식은 자동으로 그려집니다. 파일은 Mac에만 남습니다.", "덱", "클립보드", "목록에서 제거", "Finder에서 보기", "카드를 찾을 수 없습니다. 파일에 질문과 답의 두 열이 필요합니다.", "파일을 읽을 수 없습니다.", "질문", "답", "클릭하여 답 보기", "클릭하여 질문 보기", "모름", "알아요", "셔플", "진행 상황 재설정", "진행 상황을 재설정하겠습니까?", "모든 평가가 제거됩니다. 카드는 그대로 남습니다.", "재설정", "취소", "덱 끝!", "전체", "틀린 카드 반복", "전체 반복", "모두 알고 있습니다!", "걱정 마세요. 다시 한 번 살펴보세요!", "모르는 카드를 반복해서 익히세요.", "평가 안 함: %d", "듣기", "카드 뒤집기", "이전 카드", "다음 카드", "덱", "최근 사용 열기", "메뉴 지우기", "첫 번째 카드", "마지막 카드"],
    ]
}
